# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'IBdesignDemo' do
pod 'Kingfisher', '~> 2.4'
pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'TwitterCore'
pod ‘Koloda’
pod 'AlamofireNetworkActivityIndicator'
pod 'AlamofireImage'
end

